[package]
name = "lib_2"
version = "0.1.0"
authors = ["Sonor <ghsonor@gmail.com>"]
path = "src/main.rs"
default-run = "lib_2"
edition = "2018"


[lib]
name = "lib"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
