[package]
name = "curses-guessing-game"
version ="0.1.0"
authors = ["kelemzol@elte.hu"]


[dependencies]
rand = "0.3.14"
#pancurses = "0.16"

[dependencies.pancurses]
version = "0.16"
features = ["win32"]
